Fix compilation error due to use of host headers
Right now compilation fails on s390x and ppc64le with the following
error message:

  /usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
  # include <gnu/stubs-32.h>
            ^~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [Makefile:68: .output/sysctl.bpf.o] Error 1

The reason is that /usr/include/gnu/stubs.h assume if the macro for
64-bit system is not defined then we're targeting the 32-bit systems,
for example, on x86_64 we have:

    #if !defined __x86_64__
    # include <gnu/stubs-32.h>
    #endif
    #if defined __x86_64__ && defined __LP64__
    # include <gnu/stubs-64.h>
    #endif
    #if defined __x86_64__ && defined __ILP32__
    # include <gnu/stubs-x32.h>
    #endif

But the root cause of this is that BPF shouldn't have been using host
headers in the first place. This commit does the following to remove use
of host headers:
- Change errno.h into linux/errno.h from kernel-devel
- Remove string.h
  - This means memset() is no longer defined, so change memset() into
    __builtin_memset()